"""
context_pool.py

Pools PooledChunks from all active source agents (arxiv, pwc, web)
into one ranked, capped list, then encodes it as TOON for the
compiler. Two concerns, kept deliberately separate:

1. pool_chunks() — merging + PER-SOURCE caps, so one noisy source
   (web is usually the noisiest) can't crowd out arxiv/pwc chunks in
   the final context, regardless of how many results each fetcher
   happened to return.
2. encode_toon() — pure formatting, no logic. Only used on the way
   IN to the compiler LLM call; never asked of an LLM to generate,
   since that's an unproven, unnecessary reliability risk.
"""

from typing import Dict, List, Optional
from models.classes import PooledChunk, Source

# Per-source cap: independent of how many results each fetcher returns.
DEFAULT_SOURCE_CAPS: Dict[Source, int] = {
    Source.ARXIV: 5,
    Source.PAPERSWITHCODE: 5,
    Source.WEB: 5,
    Source.GITHUB: 5,
}


def pool_chunks(
    chunks_by_source: Dict[Source, List[PooledChunk]],
    caps: Optional[Dict[Source, int]] = None,
) -> List[PooledChunk]:
    """
    Merge chunks from multiple sources into one pool, applying a
    per-source cap so no single source dominates. Within each source,
    keeps the highest-scoring chunks first.

    chunks_by_source: e.g. {Source.ARXIV: [...], Source.WEB: [...]}.
    Sources absent from the dict, or with an empty list, are simply
    skipped — the router may not have activated them at all.
    """
    caps = caps or DEFAULT_SOURCE_CAPS
    pooled: List[PooledChunk] = []

    for source, chunks in chunks_by_source.items():
        if not chunks:
            continue
        cap = caps.get(source, 5)
        ranked = sorted(chunks, key=lambda c: c.score, reverse=True)
        pooled.extend(ranked[:cap])

    return pooled


def _toon_escape(value: str) -> str:
    """
    CSV-style quoting: wrap in quotes and double any internal quotes
    if the value contains a comma, quote, or newline — anything that
    would otherwise break the row on parse.
    """
    if any(c in value for c in (",", '"', "\n")):
        return '"' + value.replace('"', '""') + '"'
    return value


def encode_toon(chunks: List[PooledChunk]) -> str:
    """
    Encode a pooled chunk list as TOON: one header row declaring the
    schema + row count, then one row per chunk. A uniform array of
    same-shaped objects is exactly TOON's intended use case, which
    pooled chunks are by construction (same PooledChunk shape
    regardless of which source they came from).

    INPUT-side encoding only — built programmatically here, never
    generated by an LLM, so there's no format-reliability risk.
    """
    if not chunks:
        return "chunks[0]{source,source_id,title,section,score,text}:"

    fields = ["source", "source_id", "title", "section", "score", "text"]
    header = f"chunks[{len(chunks)}]{{{','.join(fields)}}}:"

    rows = []
    for c in chunks:
        row_values = [
            c.source.value,
            _toon_escape(c.source_id),
            _toon_escape(c.title),
            _toon_escape(c.section),
            str(c.score),
            _toon_escape(c.text),
        ]
        rows.append(",".join(row_values))

    return header + "\n" + "\n".join(rows)